server:
  port: 10002

spring:
  main:
    # 允许 依赖循环
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/gulimall_pms
  cloud:
    # 配置nacos 的地址
    nacos:
      discovery:
        server-addr: localhost:8848
    # OSS云存储对象配置
    alicloud:
      access-key: LTAI5tLqPcndgvCmQ6hnqch9
      secret-key: s1K8xXFvcZnAbd37RGlRBRHHSP0ztE
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
  application:
    name: gulimall-product
#   时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    com.gmy.gulimall: debug

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

