server:
  port: 5001

spring:
  cloud:
    # 配置nacos 的地址
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gulimall-auth-server
  redis:
    port: 6379
    host: 192.168.137.104
  session:
    store-type: redis

  thymeleaf:
    cache: false

